apiVersion: apps/v1
kind: Deployment
metadata:
  name: extra-credit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poojaimg
  template:
    metadata:
      labels:
        app: poojaimg
    spec:
      containers:
      - name: M16474112container
        image: poojaimg:latest # Replace with your Docker image name
        ports:
        - containerPort: 8080